# Generated by Django 4.1.6 on 2023-02-09 02:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("event_date", models.DateTimeField()),
                ("create_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "events",
            },
        ),
    ]
