# Generated by Django 4.1.6 on 2023-02-09 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="user_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="create_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Registered in"),
        ),
    ]
