# Generated by Django 4.1.6 on 2023-02-09 02:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0002_event_user_id_alter_event_create_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="user_id",
            new_name="user",
        ),
    ]
